spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091
#          jwk-set-uri: http://localhost:8091/oauth2/jwks
logging:
  level:
    org:
      springframework:
        security: trace